[package]
name = "day1"
version = "0.1.0"
authors = ["Ch4s3r <lamprecht.patrick1@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.66"
nom = "7.1.1"
itertools = "0.10.5"
enum-iterator = "1.2.0"